elementary/dock

.gitignore
docs/install_docs.sh
docs/meson.build
lib/meson.build

meson: build docs using valadoc

---

data/ui/preferences.ui
lib/PositionManager.vala
lib/Widgets/PreferencesWindow.vala

Copy of the current patch we apply in LP

Remove zoom support

---

src/Main.vala
src/SessionManager.vala
src/meson.build

View with whitespace changes off if possible

Register with session manager

---

COPYING

For some reason license detection fails in the version that we have currently. Also updated URLS are nice

COPYING: Update URLs

---

src/Main.vala

Same as https://github.com/elementary/pantheon-agent-polkit/pull/58 (copy and paste error)

Fix end-session signal signature

---

meson.build

meson: Fix granite version

---

lib/DockRenderer.vala

DockRenderer: Use GTK Theme Accent Color in Indicators

---

meson.build
src/Application.vala

This makes use of Valas experimental local functions. Are we using them/is it save to use them? Or should I switch it to a normal function/no function?

Support dark mode

---

data/Application.css
data/dock.gresource.xml
src/Application.vala
src/Launcher.vala

Launcher: add Unity Progress support

---

src/Launcher.vala

Launcher: fallback to application-default-icon

---

src/App.vala
src/AppWindow.vala
src/DesktopIntegration.vala
src/Launcher.vala
src/LauncherManager.vala

Scrolling on top of a launcher icon will cycle through the windows.
Better with elementary/gala#1884

Implement scrolling to switch windows

---

src/App.vala
src/Launcher.vala

Fixes #77
Check if appinfo contains a single window hint or a new window action and try to launch a new instance if so. Otherwise, beep

Launch new instance on middle click

---

data/dock.metainfo.xml.in
data/meson.build
po/extra/LINGUAS
po/extra/POTFILES
po/extra/extra.pot
po/extra/fr.po
po/extra/hu.po
po/extra/meson.build
po/extra/ru.po
po/extra/uk.po
po/meson.build

Add Metainfo

---

debian/control

Control: add recommends switcheroo

---

src/Launcher.vala
src/LauncherManager.vala

We are dealing with some more or less complicated stuff and some fancy calculations so I guess it cant hurt to add some comments for the future

Add some more comments

---

src/Launcher.vala

Fixes #251 
To test you can use (shameless self advertisement) https://github.com/leolost2605/detective launch it with ctrl and space and then immediately press esc to close the window again

Launcher: Fix crash on rapid revealing/unrevealing

---

data/dock.metainfo.xml.in
meson.build

Release 8.0.0

---

src/LauncherManager.vala

LauncherManager: Reset size request after animation finishes

---

src/Launcher.vala

Fixes #279 
I haven't observed the memory issue with this branch so it might be related and thus fixed.
This will still lead to the (comparatively) high cpu usage if a progressbar is visible but since that's not often the case I guess it's a good middle ground for keeping the feature and still cpu consumption low :shrug:

Only keep progressbar while needed

---

data/dock.metainfo.xml.in
src/Launcher.vala

Launcher: Pin app on drag

---

data/dock.metainfo.xml.in
src/Launcher.vala

Launcher: Only act on actual scrolls not begin

---

data/Application.css

Fixes https://github.com/elementary/dock/issues/321

Add spacing between icon and running indicator

---

data/Application.css
src/MainWindow.vala

Based on https://github.com/elementary/dock/pull/307
Fixes https://github.com/elementary/dock/issues/275

Fix icons clipping when bouncing and separate background from window

---

data/Application.css
src/WorkspaceSystem/IconGroup.vala

Add basic workspace switcher styles

CSS: add workspace switcher styles

---

data/Application.css
src/MainWindow.vala
src/WorkspaceSystem/IconGroup.vala

Makes the reduce transparency styles more contrasty. It's pretty subtle, easier to see in dark style:

Improve high contrast styles

---

data/Application.css
src/MainWindow.vala

Reducing diff of https://github.com/elementary/dock/pull/361
Unrelated changes from https://github.com/elementary/dock/pull/365

Move reduce transparency to main window

---

src/Application.vala
src/DBus/GalaDBus.vala
src/WorkspaceSystem/Workspace.vala
src/meson.build

Open MultitaskingView when clicking active workspace

---

src/WorkspaceSystem/DynamicWorkspaceItem.vala

DynamicWorkspaceItem: open multitasking if clicked again

---

src/AppSystem/Launcher.vala

In addition to secondary click for touch

Support long press on launchers

---

meson.build
src/AppSystem/App.vala
src/AppSystem/AppSystem.vala
src/DBus/Unity.vala
src/ItemManager.vala
src/WindowSystem/WindowSystem.vala
src/WorkspaceSystem/DynamicWorkspaceItem.vala
src/WorkspaceSystem/IconGroup.vala
src/WorkspaceSystem/Workspace.vala
src/WorkspaceSystem/WorkspaceSystem.vala

Everything we need is already in GLib.

Remove dependency on libgee

---

src/ItemManager.vala

Fixes https://github.com/elementary/dock/issues/391

Fix crash and visual bugs with animations disabled

---

data/dock.metainfo.xml.in
src/MainWindow.vala

Closes https://github.com/elementary/dock/issues/400

Fix dock bounds when hide mode is 'Never'

---

data/dock.metainfo.xml.in
meson.build

Release 8.1.1

---

data/dock.metainfo.xml.in
meson.build

Contains a small optimization that https://github.com/elementary/gala/pull/2374 relies on

Release 8.1.2

---

data/dock.metainfo.xml.in
meson.build

Contains lots of good bug fixes plus background apps

Release 8.2.0
