elementary/dock

lib/meson.build
Matches what is done with Autotools, also fixes all the applications linking to it.
=> meson: Fix libplank soversion

.github/workflows/main.yml, lib/DockRenderer.vala, lib/Drawing/Theme.vala, lib/Widgets/DockWindow.vala, meson.build, tests/headless_runner.sh, tests/meson.build
Depends on https://github.com/elementary/stylesheet/pull/609 and Granite 5.4.
=> Support Granite dark style preference

meson.build
Using `.format` on strings that are paths isn't a good idea.
=> build: use join_paths for pkgconf

lib/DockRenderer.vala, lib/Drawing/DockTheme.vala
Since now GTK window styling has improved, having a `backdrop` distinction between inactive and active windows, this dock glow is not needed anymore.
=> Styling: Remove Active Window Dock Glow

lib/Items/DockElement.vala
Set it to 48 chars by default.
Supersedes https://github.com/elementary/dock/pull/19
=> DockElement: Ellipsize all the MenuItems if they contain too many characters

meson.build
Fixes build warnings like:
```
WARNING: Project specifies a minimum meson_version '>= 0.49.0' but uses features which were added in newer versions:
* 0.50.0: {'install arg in configure_file'}
```
=> Meson: bump minimum version to 0.50

lib/Items/ApplicationDockItem.vala
Resolve #165
The implementation is a bit hacky, but I tried to keep the scope of changes as small as possible considering planned Dock rewrite.
Can be tested using [a demo app](https://github.com/Antolius/actions-launcher-demo):
[showcase-of-action-activation-from-dock.webm](https://user-images.githubusercontent.com/5374391/187310883-a356bc6f-079f-4fa3-a3d6-3a2cce1fd7f1.webm)
=> Update action launching in ApplicationDockItem

meson.build, src/Launcher.vala, src/MainWindow.vala
- Keep in Dock
- Launch with desktop actions
- ~It has a close button that shows up when there are open windows but it doesn't do anything because AFAIK there currently isn't a way to close other applications~
Compared to the plank menu it now has an arrow that's pointing to the icon, should we keep it? 
The popover currently doesn't close when clicking outside the dock which [is a X Server bug](https://gitlab.gnome.org/GNOME/gtk/-/issues/3502).
Fixes #55
Fixes #86
=> Add context menu

data/meson.build, meson.build, src/Launcher.vala
* fix a issue with clang-15 having a compilation error when using a uint64 in `GLib.List.search()`.
* fix a linker error by missing `-lm` in the flags.
* fix meson's deprecations.
=> Fix some small issues

src/Application.vala, src/DBus/Unity.vala, src/Launcher.vala, src/LauncherManager.vala, src/MainWindow.vala, src/meson.build
Fixes #74 
Fixes #201 
Tested with Granite Demo. The DBus class is taken almost directly from Plank with code style fixes.
=> Add support for Unity badges

src/Launcher.vala, src/LauncherManager.vala
Add an action group to every launcher and move all logic regarding action activation etc. there. Simplifies the codebase quite a bit
=> Move action and action group logic to Launcher

src/DesktopIntegration.vala, src/Launcher.vala, src/LauncherManager.vala
Launch the gala window spread when more than one window is open and the Launcher is clicked.
Requires elementary/gala#1833
=> Integrate with gala window spread

debian/rules
Taken from https://github.com/elementary/switchboard-plug-parental-controls/blob/deb-packaging/debian/rules
Mabye fixes #213
=> Rules: enable systemd service

po/POTFILES, src/App.vala, src/DesktopIntegration.vala, src/Launcher.vala, src/LauncherManager.vala, src/meson.build
Since we are going to add quite a bit more functionality regarding e.g. launching a new window of an app, cycling through windows, checking which workspace we are one etc. and since the launcher class was becoming quite big with it being responsible for both UI and functionality I think it would be good to separate out a new App class which takes responsibility for launching/activating a window/showing a spread/unity stuff/etc.
=> Introduce an App class taking responsibility from the Launcher

src/App.vala, src/DesktopIntegration.vala
For apps that aren't doing single instance management (e.g. gnome calculator i think) or open new windows on repeated activations (e.g. firefox i think) currently clicking the launcher will launch a new instance/window. This PR will activate the open window instead. 
If multiple windows are open the spread is shown like before.
=> Focus window on click

src/App.vala, src/DesktopIntegration.vala, src/Launcher.vala, src/LauncherManager.vala
Sometimes it happens that a DBus call freezes (?) which makes the app unresponsive. This will make all DBus calls asynchronous so that if that happens it will just eventually timeout.
=> Do DBus calls asynchronously

debian/rules
Reverts elementary/dock#214
The systemd unit file is removed in #234
=> Revert "Rules: enable systemd service"

src/LauncherManager.vala
When you would reorder a launcher e.g. from the far right to the far left and then do something so that reposition launchers would be called (e.g. launch an app that's not pinned, remove a pinned app, etc.) the launcher that was moved would animate a move from its original position to its current position even though it shouldn't move/animate at all. With this we make sure that we move only via the launchers animate_move so that its current_pos stays in sync with its actual current x
=> Some move after move glitch fixes

data/dock.gschema.xml, src/Application.vala, src/DBus/ShellKeyGrabber.vala, src/LauncherManager.vala, src/meson.build
Fixes #66 
This will now grab the accelerators via DBus as suggested by @lenemter. I'd leave the commandline option still in there since it might come in handy in some custom scripts/commands people might want to do. But if we'd rather remove it that's fine to.
=> Allow launching apps via keyboard shortcuts

data/dock.gschema.xml
We added Files to the Plank in elementary/default-settings#271, so I think we should add it to our new dock too.
=> gschema: Add Files to dock

src/Launcher.vala, src/LauncherManager.vala
Fixes a memory leak where launchers weren't freed when they were removed
=> Fix leaking Launchers

meson.build, src/App.vala, src/Launcher.vala, src/LauncherManager.vala
Fixes a memory leak where apps weren't freed when they weren't needed anymore. 
We switch from glib.hashtable and glib.list s here to gee since working with the glib variants from vala code is hard when you want to not leak memory since it's designed with c in mind i guess (e.g. take will not unref the key and value). So why not use gee which was designed for vala.
This will only actually free apps with #249 since launchers hold a reference on apps.
=> Fix memory leak with apps

data/Application.css, src/App.vala, src/AppWindow.vala, src/Launcher.vala, src/LauncherManager.vala
Add a small dot under the app if there is a window in the current workspace.
Goes with https://github.com/elementary/gala/pull/1977
Fixes #30
=> Launcher: Add running on current workspace indicator

data/dock.gschema.xml
Fixes #239 
If installer isn't present (like after installation) it will just be autoremoved
=> GSettings: add installer to default launchers

data/dock.metainfo.xml.in, src/App.vala, src/Launcher.vala
We keep animating until either a window appears or 10 seconds are over.
Fixes #171
I'm not to happy with the animation so someone from @elementary/ux should probably take a look. Currently it seems to slow when going over to the bounce down but keeping the 200 ms feel to fast when having to wait for an app to launch. We could also just do the normal bounce up and down and if the app hasn't launched by then we alternate its opacity?
Any ideas are welcome, also feel free to just push to this branch :)
=> Launcher: Keep animating until app was launched

src/App.vala
Fixes the multitasking view icon bouncing for the full 10 seconds.
=> App: Respect startup notify key for launching animation

meson.build
We now require GLib 2.74 here.
=> meson: Specify minimum GLib version

src/BaseItem.vala, src/ItemManager.vala
Reducing diff of https://github.com/elementary/dock/pull/361
We call `set_revealed` twice -- when the icon created and when the icon is being removed. Because of this we remove the item twice which produces warning: `gtk_fixed_remove: assertion 'gtk_widget_get_parent (widget) == GTK_WIDGET (fixed)' failed`
Also I included minor comments/methods signature changes
=> Fix warnings

data/dock.gschema.xml
Now that we have the workspace switcher and it's easy to get to the multitasking view via #384 and #385, this dock item seems less necessary
=> GSchema: remove multitasking from defaults

src/WindowSystem/Window.vala, src/WorkspaceSystem/WorkspaceSystem.vala
Requires https://github.com/elementary/gala/pull/2285
=> WorkspaceSystem: sort windows by time they appeared on the workspace

src/AppSystem/Launcher.vala, src/BaseItem.vala, src/ItemManager.vala, src/WindowSystem/DesktopIntegration.vala, src/WorkspaceSystem/DynamicWorkspaceItem.vala, src/WorkspaceSystem/IconGroup.vala, src/WorkspaceSystem/Workspace.vala, src/WorkspaceSystem/WorkspaceSystem.vala
Fixes #381 
Requires elementary/gala#2320
A few things:
- when dragging and dropping the badge and progress are now attached to the icon which is IMO a bit cooler but can be easily changed back
- we use Gee.List because it's more suitable for the vala way of doing things. also use arraylist because we do a bunch of random access
- move all of the file dnd handling to the single file drop target in item manager. This prevents some races between multiple drop targets where the drop sometimes would be done on the one for the launchers and sometimes on the big one.
=> Implement workspace reordering with drag and drop

meson.build, meson_options.txt, src/ItemManager.vala
So we can continue to make bugfix etc releases while we continue to work on the workspace switcher
After merging we can change the LP recipe to use this packaging branch in daily: https://github.com/elementary/dock/tree/deb-packaging-daily
=> Make workspace switcher optional

data/dock.gschema.xml
Reverts elementary/dock#386
Revert this for now since we're building workspace switcher optionally. We can revert reverting when workspace switcher builds by default :)
=> Revert "GSchema: remove multitasking from defaults"

src/MainWindow.vala
What we currently achieve by setting a custom size via our wayland protocol is actually supported by default in wayland via the shadow width which maps to frame rect and buffer rect in mutter. I only found out about shadow width recently so I always thought frame rect and buffer rect are somewhat broken or rather use something else :grimacing: 
Setting the shadow width ourselves allows us to remove the custom size method from our wayland protocol and the custom rect handling which has caused a few issues in the past because of wrong coordinate conversion on different scaling factors and methods. (See elementary/wingpanel#568, elementary/wingpanel#594, elementary/gala#2139, etc.)
Fixes #351 (On X that requires a dock restart for some reason? I think that's due to a bug in gala but I will …
=> Use shadow width instead of custom size

data/Application.css, src/AppSystem/Launcher.vala
This is an idea on how to solve the issue of unreadable tooltips (#422) by replacing them with nicer popovers.
I wasn't sure how to add the required padding without affecting the already existing popover for the menu and so I added a custom CSS class. This could probably be solved more elegantly.
Fixes https://github.com/elementary/dock/issues/422
Fixes https://github.com/elementary/dock/issues/324
Fixes https://github.com/elementary/dock/issues/29
Closes https://github.com/elementary/dock/pull/206
=> Replace tooltip with popover

data/Application.css
In light mode, particularly when transparency was reduced or a window with a light background was behind the dock, the indicator would disappear.
=> Styles: Fix "Active on Other Workspace" indicator color

data/Application.css
Now that we have blur, increase the transparency effect a bit
=> Styles: increase transparency

src/ItemManager.vala, src/MainWindow.vala
Changes in ItemManager:
- Add missing `#if WORKSPACE_SWITCHER` for separator
- Use `settings.changed["icon-size"]`instead of manually checking the key
Changes in MainWindow:
- Container doesn't use Gtk.Box, so make it subclass Gtk.Widget instead
- Avoid retrieving surface in signal handlers, the surface is already passed into handlers automatically
=> Small cleanup
